# -*- coding: utf-8 -*-
"""student_placement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vq3AmNd26BVD-2qye2hwy4kaoLsGI_JH
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/placement (1).csv')

df.head()

df.shape

df = df.iloc[:,1:]

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

X = df.iloc[:,0:2]
y = df.iloc[:,-1]

X

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

X_train

y_train

X_test

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_train

"""X_test = scaler.transform(X_test)"""

X_test

"""**Model traning **"""

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train,y_train)

pred = clf.predict(X_test)

y_test

"""**Accuracy test**

"""

from sklearn.metrics import accuracy_score

accuracy_score(y_test,pred)

from mlxtend.plotting import plot_decision_regions

plot_decision_regions(X_train, y_train.values, clf=clf, legend=2)

import pickle

pickle.dump(clf,open('model.pkl','wb'))